/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Sun Jan 25 13:28:40 2015. */

#ifndef PB_GRPC_DATA_PB_H_INCLUDED
#define PB_GRPC_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _google_internal_cloudlatencytest_v2_AggregatedStats {
    pb_callback_t stats;
} google_internal_cloudlatencytest_v2_AggregatedStats;

typedef struct _google_internal_cloudlatencytest_v2_AggregatedStatsReply {
    pb_callback_t test_value;
} google_internal_cloudlatencytest_v2_AggregatedStatsReply;

typedef struct _google_internal_cloudlatencytest_v2_StatsReply {
    pb_callback_t test_value;
} google_internal_cloudlatencytest_v2_StatsReply;

typedef struct _google_internal_cloudlatencytest_v2_StringValue {
    pb_callback_t label;
    pb_callback_t value;
} google_internal_cloudlatencytest_v2_StringValue;

typedef struct _google_internal_cloudlatencytest_v2_DoubleValue {
    pb_callback_t label;
    bool has_value;
    float value;
} google_internal_cloudlatencytest_v2_DoubleValue;

typedef struct _google_internal_cloudlatencytest_v2_IntValue {
    pb_callback_t label;
    bool has_value;
    int64_t value;
} google_internal_cloudlatencytest_v2_IntValue;

typedef struct _google_internal_cloudlatencytest_v2_Stats {
    bool has_time;
    double time;
    pb_callback_t int_values;
    pb_callback_t double_values;
    pb_callback_t string_values;
} google_internal_cloudlatencytest_v2_Stats;

/* Default values for struct fields */

/* Initializer values for message structs */
#define google_internal_cloudlatencytest_v2_IntValue_init_default {{{NULL}, NULL}, false, 0}
#define google_internal_cloudlatencytest_v2_DoubleValue_init_default {{{NULL}, NULL}, false, 0}
#define google_internal_cloudlatencytest_v2_StringValue_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define google_internal_cloudlatencytest_v2_Stats_init_default {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_internal_cloudlatencytest_v2_AggregatedStats_init_default {{{NULL}, NULL}}
#define google_internal_cloudlatencytest_v2_StatsReply_init_default {{{NULL}, NULL}}
#define google_internal_cloudlatencytest_v2_AggregatedStatsReply_init_default {{{NULL}, NULL}}
#define google_internal_cloudlatencytest_v2_IntValue_init_zero {{{NULL}, NULL}, false, 0}
#define google_internal_cloudlatencytest_v2_DoubleValue_init_zero {{{NULL}, NULL}, false, 0}
#define google_internal_cloudlatencytest_v2_StringValue_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define google_internal_cloudlatencytest_v2_Stats_init_zero {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define google_internal_cloudlatencytest_v2_AggregatedStats_init_zero {{{NULL}, NULL}}
#define google_internal_cloudlatencytest_v2_StatsReply_init_zero {{{NULL}, NULL}}
#define google_internal_cloudlatencytest_v2_AggregatedStatsReply_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define google_internal_cloudlatencytest_v2_AggregatedStats_stats_tag 1
#define google_internal_cloudlatencytest_v2_AggregatedStatsReply_test_value_tag 99
#define google_internal_cloudlatencytest_v2_StatsReply_test_value_tag 99
#define google_internal_cloudlatencytest_v2_StringValue_label_tag 1
#define google_internal_cloudlatencytest_v2_StringValue_value_tag 2
#define google_internal_cloudlatencytest_v2_DoubleValue_label_tag 1
#define google_internal_cloudlatencytest_v2_DoubleValue_value_tag 2
#define google_internal_cloudlatencytest_v2_IntValue_label_tag 1
#define google_internal_cloudlatencytest_v2_IntValue_value_tag 2
#define google_internal_cloudlatencytest_v2_Stats_time_tag 1
#define google_internal_cloudlatencytest_v2_Stats_int_values_tag 2
#define google_internal_cloudlatencytest_v2_Stats_double_values_tag 3
#define google_internal_cloudlatencytest_v2_Stats_string_values_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t google_internal_cloudlatencytest_v2_IntValue_fields[3];
extern const pb_field_t google_internal_cloudlatencytest_v2_DoubleValue_fields[3];
extern const pb_field_t google_internal_cloudlatencytest_v2_StringValue_fields[3];
extern const pb_field_t google_internal_cloudlatencytest_v2_Stats_fields[5];
extern const pb_field_t google_internal_cloudlatencytest_v2_AggregatedStats_fields[2];
extern const pb_field_t google_internal_cloudlatencytest_v2_StatsReply_fields[2];
extern const pb_field_t google_internal_cloudlatencytest_v2_AggregatedStatsReply_fields[2];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
