/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Sun Jan 25 13:28:40 2015. */

#include "grpc_data.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t google_internal_cloudlatencytest_v2_IntValue_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, google_internal_cloudlatencytest_v2_IntValue, label, label, 0),
    PB_FIELD(  2, INT64   , OPTIONAL, STATIC  , OTHER, google_internal_cloudlatencytest_v2_IntValue, value, label, 0),
    PB_LAST_FIELD
};

const pb_field_t google_internal_cloudlatencytest_v2_DoubleValue_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, google_internal_cloudlatencytest_v2_DoubleValue, label, label, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, google_internal_cloudlatencytest_v2_DoubleValue, value, label, 0),
    PB_LAST_FIELD
};

const pb_field_t google_internal_cloudlatencytest_v2_StringValue_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, google_internal_cloudlatencytest_v2_StringValue, label, label, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, google_internal_cloudlatencytest_v2_StringValue, value, label, 0),
    PB_LAST_FIELD
};

const pb_field_t google_internal_cloudlatencytest_v2_Stats_fields[5] = {
    PB_FIELD(  1, DOUBLE  , OPTIONAL, STATIC  , FIRST, google_internal_cloudlatencytest_v2_Stats, time, time, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, google_internal_cloudlatencytest_v2_Stats, int_values, time, &google_internal_cloudlatencytest_v2_IntValue_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, google_internal_cloudlatencytest_v2_Stats, double_values, int_values, &google_internal_cloudlatencytest_v2_DoubleValue_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, google_internal_cloudlatencytest_v2_Stats, string_values, double_values, &google_internal_cloudlatencytest_v2_StringValue_fields),
    PB_LAST_FIELD
};

const pb_field_t google_internal_cloudlatencytest_v2_AggregatedStats_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, google_internal_cloudlatencytest_v2_AggregatedStats, stats, stats, &google_internal_cloudlatencytest_v2_Stats_fields),
    PB_LAST_FIELD
};

const pb_field_t google_internal_cloudlatencytest_v2_StatsReply_fields[2] = {
    PB_FIELD( 99, STRING  , OPTIONAL, CALLBACK, FIRST, google_internal_cloudlatencytest_v2_StatsReply, test_value, test_value, 0),
    PB_LAST_FIELD
};

const pb_field_t google_internal_cloudlatencytest_v2_AggregatedStatsReply_fields[2] = {
    PB_FIELD( 99, STRING  , OPTIONAL, CALLBACK, FIRST, google_internal_cloudlatencytest_v2_AggregatedStatsReply, test_value, test_value, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(google_internal_cloudlatencytest_v2_Stats, int_values) < 65536 && pb_membersize(google_internal_cloudlatencytest_v2_Stats, double_values) < 65536 && pb_membersize(google_internal_cloudlatencytest_v2_Stats, string_values) < 65536 && pb_membersize(google_internal_cloudlatencytest_v2_AggregatedStats, stats) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_google_internal_cloudlatencytest_v2_IntValue_google_internal_cloudlatencytest_v2_DoubleValue_google_internal_cloudlatencytest_v2_StringValue_google_internal_cloudlatencytest_v2_Stats_google_internal_cloudlatencytest_v2_AggregatedStats_google_internal_cloudlatencytest_v2_StatsReply_google_internal_cloudlatencytest_v2_AggregatedStatsReply)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(google_internal_cloudlatencytest_v2_Stats, int_values) < 256 && pb_membersize(google_internal_cloudlatencytest_v2_Stats, double_values) < 256 && pb_membersize(google_internal_cloudlatencytest_v2_Stats, string_values) < 256 && pb_membersize(google_internal_cloudlatencytest_v2_AggregatedStats, stats) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_google_internal_cloudlatencytest_v2_IntValue_google_internal_cloudlatencytest_v2_DoubleValue_google_internal_cloudlatencytest_v2_StringValue_google_internal_cloudlatencytest_v2_Stats_google_internal_cloudlatencytest_v2_AggregatedStats_google_internal_cloudlatencytest_v2_StatsReply_google_internal_cloudlatencytest_v2_AggregatedStatsReply)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

